AWSTemplateFormatVersion: 2010-09-09
Description: 
Parameters:
  #------------------------------------------------------------#
  # Input Parameters
  # 環境名、システム名、サブシステム名(Environment,Systemname,
  # Subsystemname)を各リソース名に使用する。
  #------------------------------------------------------------#
  AccountID:
    Type: String
    Default: ""

  # 環境名
  Environment: 
    Description: "Please input Environment."
    Type: String
    Default: "stg"
    AllowedValues: 
      - "prod" # 本番
      - "stg" # ステージング
      - "dev" # 開発
    ConstraintDescription: ""
  
  # システム名
  Systemname: 
    Description: "Please input Systemname."
    Type: String
    Default: ""
    AllowedPattern: "[a-z0-9]+"
    ConstraintDescription: "Malformed input-Parameter MyParameter must match pattern [a-z0-9]+"
  
  # サブシステム名
  Subsystemname:
    Description: "Please input Subsystemname.(ex.test)"
    Type: String
    Default: "fh"
    AllowedPattern: "[a-z0-9]+"
    ConstraintDescription: "Malformed input-Parameter MyParameter must match pattern [a-z0-9]+"

#ブランチ
  branchname:
    Description: "Please input Subsystemname.(ex.test)"
    Type: String
    Default: "develop"
    AllowedValues: 
      - "master" # 本番
      - "develop" # ステージング
      - "feature" # 開発
    ConstraintDescription: ""
    ConstraintDescription: "Malformed input-Parameter MyParameter must match pattern [a-z0-9]+"

Metadata:
  "AWS::CloudFormation::Interface": 
    ParameterGroups: 
      - Label: 
          default: "Common"
        Parameters: 
          - Environment
          - Systemname
          - Subsystemname
          - branchname


# 各種パラメータ


# 各種リソース
Resources:
#cloudformation


  # CodePipeLine
  # 内容は CodeCommit → CodeBuild → CodeDeploy の順で処理をして、最終的にECRにDockerイメージをPushする
  # DockerイメージをPushするのはCodeDeploy
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStores:
          - Region: us-east-1
            ArtifactStore:
              Type: S3
              Location: !Sub cicd

          - Region: ap-northeast-1
            ArtifactStore:
              Type: S3
              Location: !Ref S3Bucket1

      Name: !Sub -if
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              Namespace: SourceVariables
              Configuration:
                PollForSourceChanges: true
                RepositoryName: -fh
                BranchName: !Sub ${branchname}
              RunOrder: 1
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Namespace: BuildVariables
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
        - Name: Deploy-wafv2
          Actions:
            - Name: wafv2
              Region: us-east-1
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Namespace: StagingVariables-wafv2
              Configuration:
                ParameterOverrides: !Sub |
                    {
                    "Environment": "",
                   "IPRestrictionBlackList": "",
                    "IPRestrictionBlockRateLimit": "0",
                    "AWSManagedRulesCommonRuleSet": "Yes",
                    "AWSManagedRulesAmazonIpReputationList": "Yes",
                    "AWSManagedRulesAnonymousIpList": "Yes",
                    "Systemname": "",
                    "Subsystemname": "fh"
                    }
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND,CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt cloudformationServiceRole.Arn
                StackName: !Sub wafv2-for-s3-cloudfront-stack
                TemplatePath: BuildArtifact::wafv2.yml
              RunOrder: 1
              InputArtifacts:
                - Name: BuildArtifact
        - Name: Deploy-s3-cloudfront
          Actions: 
            - Name: s3-cloudfront
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Namespace: StagingVariables-s3-cloudfront
              Configuration:
                ParameterOverrides: !Sub |
                  {
                  "MediaConvertEndpoint": "https://mpazqbhuc..ap-northeast-1.amazonaws.com",
                  "Environment": "",
                  "Systemname": "",
                  "CloudFrontCustomDNS": "Yes",
                  "CloudfrontDNSHostName": ""
                  }
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND,CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt cloudformationServiceRole.Arn
                StackName: s3-cloudfront
                TemplatePath: BuildArtifact::package.yaml
              RunOrder: 1
              InputArtifacts:
                - Name: BuildArtifact

